# Name for dataset. User chosen.
title: "eooffshore_ics_ccmp_v02_1_nrt_wind"
# Description of dataset.  User chosen, roughly 1 sentence in length.
description: "EOOffshore Project (https://eooffshore.github.io) 2015 - 2021 Cross-Calibrated Multi-Platform (CCMP) v0.2.1.NRT 6-hourly wind products for the Irish Continental Shelf region, where wind speed and direction have been calculated from the uwnd and vwnd variables." 
# Version of pangeo_forge_recipes library that was used 
pangeo_forge_version: "0.9.0"
pangeo_notebook_version: "2022.05.02"
# The recipes section tells Pangeo Cloud where to find the recipes within your PR.
# Many recipe PRs will have just 1 recipe, in which case this section will look similar to the example below.
# If your PR contains multiple recipes, you may add additional elements to the list below.
recipes:
  # User chosen name for recipe. Likely similiar to dataset name, ~25 characters in length
  - id: eooffshore_ics_ccmp_v02_1_nrt_wind
    # The `object` below tells Pangeo Cloud specifically where your recipe instance(s) are located and uses the format <filename>:<object_name>
    # <filename> is name of .py file where the Python recipe object is defined.
    # For example, if <filename> is given as "recipe", Pangeo Cloud will expect a file named `recipe.py` to exist in your PR.
    # <object_name> is the name of the recipe object (i.e. Python class instance) _within_ the specified file.
    # For example, if you have defined `recipe = XarrayZarrRecipe(...)` within a file named `recipe.py`, then your  `object` below would be `"recipe:recipe"`
    object: "recipe:recipe"
provenance:
  # Data provider object.  Follow STAC spec.
  # https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#provider-object
  providers:
    - name: "Remote Sensing Systems (RSS)"
      description: "Remote Sensing Systems is a world leader in processing and analyzing microwave data collected by satellite microwave sensors, whose mission is to provide research-quality geophysical data to the global scientific community."
      roles:
        - produce
        - licensor
      url: https://www.remss.com/measurements/ccmp/
  # This is a required field for provider. Follow STAC spec
  # https://github.com/radiantearth/stac-spec/blob/master/collection-spec/collection-spec.md#license
  license: "CC-BY-4.0" # https://rda.ucar.edu/datasets/ds745.1/
maintainers:
  # Information about recipe creator. name and github are required
  - name: "Derek O'Callaghan"
    orcid: "0000-0003-0585-8631"
    github: derekocallaghan
# The specific bakery (i.e. cloud infrastructure) that your recipe will run on.
# Available bakeries can be found on the Pangeo Forge website https://pangeo-forge.org/dashboard/bakeries
bakery:
  id: "pangeo-ldeo-nsf-earthcube"
