title: 'MAR Greenland'
description: 'Reconstructions of the 1900–2015 Greenland ice sheet surface mass
balance using the regional climate MAR model'
recipes:
  - id: mar-greenland
    object: 'recipe:recipe'
provenance:
  providers:
    - name: 'Google Bucket ldeo-glaciology'
      description: 'Data repository for the Polar Geophysics Group at Lamont-Doherty Earth Observatory, Columbia University'
      roles:
        - licensor
      url: https://tc.copernicus.org/articles/11/1015/2017/
  license: 'CC-BY-4.0'
maintainers:
  - name: 'Raf Antwerpen'
    orcid: '0000-0002-2313-260X'
    github: raf-antwerpen
bakery:
  id: 'pangeo-ldeo-nsf-earthcube'
